### ISSUE TITLE
检索的时候，应该去除重复的插件

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#11]
<img width="688" alt="image" src="https://github.com/WtecHtec/ext-shoot/assets/50035229/3963d4ae-eeb1-4625-94ba-82d440aa75f2">

recent、all、dev，经常会对一个插件重复展示三次

用户检索一般只想要快速找到，所以应该去重一下~

**Comment by WtecHtec** [comment]
Uploading QQ录屏20240325111110.mp4…
