### ISSUE TITLE
怎加主命令 Search Store，输入任意名字，可以直接搜索并展示chrome web store的结果

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#14]
参考npmjs https://www.npmjs.com/package/chrome-extension-meta

这类command都可以接受一个参数，当input输入框有内容的时候，回车调用就会进入此命令状态

![CleanShot 2024-03-23 at 23 56 15@2x](https://github.com/WtecHtec/ext-shoot/assets/50035229/b92580a5-e8d0-4c01-bd23-525a1cd830d6)

<img width="828" alt="CleanShot 2024-03-23 at 23 59 02@2x" src="https://github.com/WtecHtec/ext-shoot/assets/50035229/1de176e6-c4b6-4ffc-b04f-d72c4b238a6c">

Search Store 可以参考raycast上npm search的交互，简单处理，list ext的icon，title、描述，打分，安装数，回车就进入chrome 的详情页，

也可以像douban和raycast extension复杂处理，直接在cmdk界面中展示插件信息（描述、宣传图、内容、打分等等）

<img width="832" alt="CleanShot 2024-03-24 at 00 00 23@2x" src="https://github.com/WtecHtec/ext-shoot/assets/50035229/e010cff8-c75e-433e-8fd0-7d65c919a746">

https://github.com/WtecHtec/ext-shoot/assets/50035229/d87c3f70-9440-443f-9c27-935749143c7b

**Comment by WtecHtec** [comment]
Uploading QQ录屏20240325111110.mp4…
