### ISSUE TITLE
如果遇到调用了需要ext-ss的命令，要做出提醒，并引导安装ext-ss

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#19]
可以先warn一个sonner，说要安装xx，然后查看更多超链接到 Github的readme

**Comment by WtecHtec** [comment]
![image](https://github.com/WtecHtec/ext-shoot/assets/42227405/fcbb9b6b-d0f0-46fe-9a00-8d09c01380db)
