### ISSUE TITLE
bug: command 的 cmdk 不因该和 extension 的cmdk显示一样

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#21]
<img width="711" alt="CleanShot 2024-03-24 at 23 31 24@2x" src="https://github.com/WtecHtec/ext-shoot/assets/50035229/c56ff225-2f50-42e1-b553-ceea69d342f4">

很多子操作对command是没意义的。。

**Comment by WtecHtec** [comment]
command  下的子操作，只显示 'Open Recent Page' 、'Open Snapshot Dialog',  Open RecentPage 这个描述是否该换？

**Comment by Leizhenpeng** [comment]
Open RecentPage 不太合适哈哈
<img width="224" alt="CleanShot 2024-03-25 at 22 12 50@2x" src="https://github.com/WtecHtec/ext-shoot/assets/50035229/3dac8b3b-fb91-44c8-8b58-6664e770b97b">

**Comment by Leizhenpeng** [comment]
就这个名字吧~

**Comment by Leizhenpeng** [comment]
recent group 下面很多subcommand 也不太合理

<img width="691" alt="CleanShot 2024-03-25 at 22 30 43@2x" src="https://github.com/WtecHtec/ext-shoot/assets/50035229/0b1a02da-4c8f-413d-ab40-939c9b627ddf">
<img width="685" alt="CleanShot 2024-03-25 at 22 31 34@2x" src="https://github.com/WtecHtec/ext-shoot/assets/50035229/e808e87c-7f76-43b2-8265-bc020fe4e02c">
