### ISSUE TITLE
样式BUG：cmd+k 的时候，主窗口会抖动。。

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#22]
https://github.com/WtecHtec/ext-shoot/assets/50035229/c69941c0-eb7c-46ff-b385-bcab3347ba46

**Comment by Leizhenpeng** [comment]
好像是影响了原来网页的document，需要fix一下

**Comment by WtecHtec** [comment]
el.style.overflow = 'hidden'  把之前出现滚动条给隐藏，布局发生变化

**Comment by Leizhenpeng** [comment]
这个bug又出现了。。
@WtecHtec

**Comment by WtecHtec** [comment]
在Popover的modal状态下，在body加了一个属性：data-scroll-locked
