### ISSUE TITLE
commad+k 的子命令中，额困看到并且启动插件的所有自定义的tab和option页面，类似我们的update和welcom那两个页面

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#23]

**Comment by WtecHtec** [comment]
或许这块可以直接读取 manifest.json 文件,🫡

**Comment by Leizhenpeng** [comment]
manifest.json 文件里面对页面的定义不完全，比如我们的manifest文件就没有说明update和welcom那两个页面

**Comment by Leizhenpeng** [comment]
比较妥善的思路是遍历源码文件夹，看html结尾的网页
![CleanShot 2024-04-02 at 10 10 28@2x](https://github.com/WtecHtec/ext-shoot/assets/50035229/e258231d-74a0-4ff6-87a1-dd5125b8eb6e)

**Comment by WtecHtec** [comment]
cmd k 目标是extension时，可以去调用 extss 相关接口，有数据就加一个 Pages 分组

**Comment by Leizhenpeng** [comment]
和extss的交互可以这样

1. 设计一个通信接口，判断extss 是否存在。
2. 设计 show in finder 业务接口
3. 设计 scan ALL Extension page 接口 （逻辑类似 update icon 可以拿到所有数据，缓存起来，不用每次调用）
4. 设计 scan One Extension Page 接口 (允许单独更新一个插件的页面，避免性能损耗）

**Comment by WtecHtec** [comment]
> cmd k 目标是extension时，可以去调用 extss 相关接口，有数据就加一个 Pages 分组

这个交互，可以满足了，而拉取所有、单独更新好像有点复杂化了 哈哈哈
