### ISSUE TITLE
recent 遇到插件名很长的时候，排版异常

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#26]
<img width="750" alt="CleanShot 2024-03-25 at 22 56 51@2x" src="https://github.com/WtecHtec/ext-shoot/assets/50035229/66c957f2-07ff-45bc-b97a-e9e72c4b6334">

**Comment by Leizhenpeng** [comment]
这个名称好像是bug，会重复。。

**Comment by Leizhenpeng** [comment]
<img width="803" alt="CleanShot 2024-03-25 at 23 02 02@2x" src="https://github.com/WtecHtec/ext-shoot/assets/50035229/f1585c53-aae9-46ba-b495-7a9f9925b21a">

**Comment by WtecHtec** [comment]
已修复，确实把name重复保存了，但是这里的样式得修改
