### ISSUE TITLE
窗口位置未居中

### ISSUE THREAD

**Issue by jingfelix** [WtecHtec/ext-shoot#27]
如图所示，ExtShoot 的窗口在启动后没有处于居中位置
<img width="1000" alt="截屏2024-03-26 18 43 51" src="https://github.com/WtecHtec/ext-shoot/assets/72600955/dceb82c2-b940-4fbc-80fd-b8bb57b021ea">

**Comment by WtecHtec** [comment]
<img width="1418" alt="image" src="https://github.com/WtecHtec/ext-shoot/assets/42227405/867f999f-7a7b-41c2-aec6-4e5765bd2e73">
