### ISSUE TITLE
search 关键词匹配无效

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#28]
https://github.com/WtecHtec/ext-shoot/assets/50035229/850bfdef-5696-4b43-9b17-351bdb3b34fd

**Comment by WtecHtec** [comment]
目前 keywords 不够智能，或许可以利用拆词

**Comment by Leizhenpeng** [comment]
不是效果不好，是完全没有搜到，是不是漏掉传keyword参数了~

**Comment by Leizhenpeng** [comment]
框架自身的keywords的效果以前测试过还行

**Comment by WtecHtec** [comment]
已修复，
