### ISSUE TITLE
部分操作不应该放到recent里面~

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#30]

**Comment by Leizhenpeng** [comment]
不应该存放的
- 增加快照
- 插件卸载
- 添加到favorite
-

最多存在一次的
- 在应用市场搜索
- 同一个插件最多在recent list出现一次，展示最近的一次操作

（WIP）

**Comment by WtecHtec** [comment]
<img width="680" alt="image" src="https://github.com/WtecHtec/ext-shoot/assets/42227405/c228bd48-1c16-49bd-8d14-46d460ef07f5">
 commands 加入 recent list

**Comment by Leizhenpeng** [comment]
<img width="717" alt="CleanShot 2024-04-02 at 12 19 59@2x" src="https://github.com/WtecHtec/ext-shoot/assets/50035229/d7a50af7-8e77-421c-bcc5-45b6d92a621f">
快照切换部分就不放了

**Comment by WtecHtec** [comment]
快照切换 数据处理有bug

**Comment by Leizhenpeng** [comment]
recent 设计思路：
1. 快速重复最近一次的操作
2. 针对回车操作，如果是command类别，就执行即可；如果是Extension，就执行最近一次action。
3. 针对cmd+k 子命令操作，除回车外，其他全部等同普通item状态
