### ISSUE TITLE
检测到新安装的插件的时候，自动往recent中增加最近插件

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#35]

**Comment by WtecHtec** [comment]
🧐检测新安装插件，或许 使用轮询？

**Comment by Leizhenpeng** [comment]
优先看有没有钩子，如果没有只能轮训了

**Comment by WtecHtec** [comment]
监听 网络请求 🙅，无法拦截本地安装、chrome web store 请求

**Comment by WtecHtec** [comment]
> 🧐检测新安装插件，或许 使用轮询？

每次 打开 去查询是不是有最新的插件安装，然后放在recent 即可，不需要轮询

**Comment by Leizhenpeng** [comment]
<img width="964" alt="CleanShot 2024-04-11 at 13 10 20@2x" src="https://github.com/WtecHtec/ext-shoot/assets/50035229/f15504b2-8309-413d-b2e8-bc90007bf647">
 amazing done!
