### ISSUE TITLE
修改产品激活快捷键到浏览器官方管理

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#4]
产品激活快捷键应该在chrome的官方业定义，这样逻辑更统一

**Comment by WtecHtec** [comment]
chrome://extensions/shortcuts 介个么？

**Comment by WtecHtec** [comment]
![image](https://github.com/WtecHtec/ext-shoot/assets/42227405/c297756b-4668-403b-a47c-cdc1e5639b12)
