### ISSUE TITLE
打开插件页面，当插件有多个版本的时候，需要去掉版本号

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#40]
<img width="751" alt="CleanShot 2024-04-11 at 21 45 50@2x" src="https://github.com/WtecHtec/ext-shoot/assets/50035229/9598f155-7045-426a-8192-30f88c08a2a7">

**Comment by WtecHtec** [comment]
根据文件夹更新时间获取最新版本文件夹路径

**Comment by Leizhenpeng** [comment]
已完成
