### ISSUE TITLE
唤起cmdk面板后，按键监听操作应该拦截传导，不影响原来的网页

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#7]
https://github.com/WtecHtec/ext-shoot/assets/50035229/da16c615-af3f-42b7-950e-f05234eeaced

看到github上在唤起cmdk之后，按键继续影响了原网页

**Comment by WtecHtec** [comment]
部分页面监听了keydown事件，尝试阻止冒泡、捕获

**Comment by WtecHtec** [comment]
npm i dom-focus-lock  可用这个解决

**Comment by WtecHtec** [comment]
阻止 input输入：  function inputListener (event) {
          // 阻止事件冒泡
          event.stopPropagation();
        }

**Comment by Leizhenpeng** [comment]
禁止的有些过度，cmd+k 也无法使用了哈哈

**Comment by Leizhenpeng** [comment]
> npm i dom-focus-lock 可用这个解决

这个有效吗~，看起来满符合这个issue的痛点哈哈
