### ISSUE TITLE
部分subcommand和command执行完之关闭cmdk界面比较合理 

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#8]
有的comand会打开新的tab页面，比如快捷键管理页，执行完之后立刻退出cmdk合理一些

比如重启、在本地文件打开、copy name这些，大部分都是一次性操作，也应该退出

参考raycast~

https://github.com/WtecHtec/ext-shoot/assets/50035229/c05045be-9be7-47e1-9464-3c8fd143e1b0

**Comment by WtecHtec** [comment]
sub command 触发之后，将会把 Popover 关闭

**Comment by Leizhenpeng** [comment]
增加了closeLauncher 方法
