### ISSUE TITLE
subcommand中的enable和disable不应该同时显示

### ISSUE THREAD

**Issue by Leizhenpeng** [WtecHtec/ext-shoot#9]
已禁入的插件显示enable，已启用的显示enable~
<img width="716" alt="CleanShot 2024-03-23 at 23 29 06@2x" src="https://github.com/WtecHtec/ext-shoot/assets/50035229/4c60580a-1ec9-449a-a22a-2668bd758ab2">

**Comment by WtecHtec** [comment]
根据类型、状态区别显示不同的操作命令
<img width="642" alt="image" src="https://github.com/WtecHtec/ext-shoot/assets/42227405/100b171a-63dc-4415-8e97-fd2a00b6d8e2">
<img width="640" alt="image" src="https://github.com/WtecHtec/ext-shoot/assets/42227405/0c6f5c48-fb04-45fd-8a8c-307d6f1e8302">
<img width="645" alt="image" src="https://github.com/WtecHtec/ext-shoot/assets/42227405/e054fc4e-2226-442b-95bb-b93fe9c0d251">
<img width="653" alt="image" src="https://github.com/WtecHtec/ext-shoot/assets/42227405/be6c54a3-03cb-4f55-a037-d28ece3e9588">
